<a href="https://colab.research.google.com/github/tisenres/amity-aiml303/blob/main/16_02_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [1]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(42)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [2]:
# TODO: Create a vector tensor
vector = torch.tensor([1, 2, 3, 4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [3]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [4]:
# TODO: Create a 3D tensor
tensor_3d = torch.arange(1, 9).reshape(2, 2, 2)

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [5]:
# TODO: Create random tensor
random_tensor = torch.rand(4, 4)

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.3416, 0.4822, 0.2558, 0.9134],
        [0.0094, 0.5620, 0.6872, 0.0050],
        [0.0014, 0.5833, 0.9187, 0.7296],
        [0.4623, 0.1335, 0.4366, 0.6199]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [6]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(3, 224, 224)

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [7]:
# TODO: Create zeros tensor
zeros = torch.zeros(5, 5)
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [8]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
ones_like = torch.ones_like(random_tensor)
print(ones_like)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [9]:
# TODO: Create range tensor
range_tensor = torch.arange(0, 21, 2)
print(range_tensor)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])


## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [10]:
# TODO: float16 tensor
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
print(f"Float16 tensor: {float16_tensor}, Dtype: {float16_tensor.dtype}")

# TODO: int64 tensor
int64_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
print(f"Int64 tensor: {int64_tensor}, Dtype: {int64_tensor.dtype}")

Float16 tensor: tensor([1., 2., 3.], dtype=torch.float16), Dtype: torch.float16
Int64 tensor: tensor([1, 2, 3]), Dtype: torch.int64


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [11]:
# TODO: Change dtype
float32_tensor = float16_tensor.type(torch.float32)
print(f"Float32 tensor: {float32_tensor}, Dtype: {float32_tensor.dtype}")

Float32 tensor: tensor([1., 2., 3.]), Dtype: torch.float32


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [12]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2, 3, 4)
print(f"Shape: {info_tensor.shape}")
print(f"Dtype: {info_tensor.dtype}")
print(f"Device: {info_tensor.device}")

Shape: torch.Size([2, 3, 4])
Dtype: torch.float32
Device: cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [13]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
added = tensor + 5
print(f"Added 5: {added}")

# TODO: Subtract 10
subtracted = tensor - 10
print(f"Subtracted 10: {subtracted}")

# TODO: Multiply by 2
multiplied = tensor * 2
print(f"Multiplied by 2: {multiplied}")

# TODO: Divide by 10
divided = tensor / 10
print(f"Divided by 10: {divided}")

Added 5: tensor([15, 25, 35])
Subtracted 10: tensor([ 0, 10, 20])
Multiplied by 2: tensor([20, 40, 60])
Divided by 10: tensor([1., 2., 3.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [14]:
# TODO: Create A and B
A = torch.rand(2, 3)
B = torch.rand(3, 2)

print(f"Tensor A:\n{A}")
print(f"Tensor B:\n{B}")

# TODO: Matrix mul using torch.mm
result_mm = torch.mm(A, B)
print(f"Result using torch.mm:\n{result_mm}")

# TODO: Matrix mul using @
result_at = A @ B
print(f"Result using @:\n{result_at}")

Tensor A:
tensor([[0.7392, 0.1859, 0.2910],
        [0.7876, 0.7029, 0.2117]])
Tensor B:
tensor([[0.9544, 0.0396],
        [0.4997, 0.9765],
        [0.1450, 0.0659]])
Result using torch.mm:
tensor([[0.8406, 0.2299],
        [1.1337, 0.7315]])
Result using @:
tensor([[0.8406, 0.2299],
        [1.1337, 0.7315]])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [15]:
agg_tensor = torch.arange(0, 101)
# TODO: Min
min_val = agg_tensor.min()
print(f"Min: {min_val}")

# TODO: Max
max_val = agg_tensor.max()
print(f"Max: {max_val}")

# TODO: Mean (note: may need to cast to float)
mean_val = agg_tensor.type(torch.float32).mean()
print(f"Mean: {mean_val}")

# TODO: Sum
sum_val = agg_tensor.sum()
print(f"Sum: {sum_val}")

Min: 0
Max: 100
Mean: 50.0
Sum: 5050


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [16]:
# TODO: Argmin
argmin_val = agg_tensor.argmin()
print(f"Argmin: {argmin_val}")

# TODO: Argmax
argmax_val = agg_tensor.argmax()
print(f"Argmax: {argmax_val}")

Argmin: 0
Argmax: 100


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [17]:
reshape_tensor = torch.arange(10)
print(f"Original tensor: {reshape_tensor}, Shape: {reshape_tensor.shape}")
# TODO: Reshape
reshaped = reshape_tensor.reshape(2, 5)
print(f"Reshaped tensor: {reshaped}, Shape: {reshaped.shape}")

Original tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), Shape: torch.Size([10])
Reshaped tensor: tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), Shape: torch.Size([2, 5])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [18]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
print(f"Tensor 1:\n{tensor1}")
print(f"Tensor 2:\n{tensor2}")

# TODO: Stack vertically (dim=0)
vertically_stacked = torch.vstack([tensor1, tensor2])
print(f"Vertically stacked:\n{vertically_stacked}")

# TODO: Stack horizontally (dim=1)
horizontally_stacked = torch.hstack([tensor1, tensor2])
print(f"Horizontally stacked:\n{horizontally_stacked}")

Tensor 1:
tensor([[0.9430, 0.5751],
        [0.7017, 0.3219]])
Tensor 2:
tensor([[0.1545, 0.9905],
        [0.6924, 0.0476]])
Vertically stacked:
tensor([[0.9430, 0.5751],
        [0.7017, 0.3219],
        [0.1545, 0.9905],
        [0.6924, 0.0476]])
Horizontally stacked:
tensor([[0.9430, 0.5751, 0.1545, 0.9905],
        [0.7017, 0.3219, 0.6924, 0.0476]])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [19]:
squeeze_tensor = torch.rand(1, 3, 1)
print(f"Original tensor: {squeeze_tensor}, Shape: {squeeze_tensor.shape}")

# TODO: Squeeze
squeezed = squeeze_tensor.squeeze()
print(f"Squeezed tensor: {squeezed}, Shape: {squeezed.shape}")

# TODO: Unsqueeze on dim=0
unsqueezed = squeezed.unsqueeze(dim=0)
print(f"Unsqueezed tensor: {unsqueezed}, Shape: {unsqueezed.shape}")

Original tensor: tensor([[[0.5707],
         [0.3450],
         [0.9354]]]), Shape: torch.Size([1, 3, 1])
Squeezed tensor: tensor([0.5707, 0.3450, 0.9354]), Shape: torch.Size([3])
Unsqueezed tensor: tensor([[0.5707, 0.3450, 0.9354]]), Shape: torch.Size([1, 3])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [20]:
image_tensor = torch.rand(3, 100, 100)
print(f"Original image tensor shape: {image_tensor.shape}")
# TODO: Permute
permuted = image_tensor.permute(1, 2, 0)
print(f"Permuted image tensor shape: {permuted.shape}")

Original image tensor shape: torch.Size([3, 100, 100])
Permuted image tensor shape: torch.Size([100, 100, 3])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [21]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(f"Original tensor:\n{index_tensor}")

# TODO: Get 5
get_5 = index_tensor[0, 1, 1]
print(f"Value 5: {get_5}")

# TODO: Get second row [4,5,6]
get_second_row = index_tensor[0, 1]
print(f"Second row: {get_second_row}")

Original tensor:
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Value 5: 5
Second row: tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [22]:
import numpy as np
numpy_array = np.array([1,2,3,4])
print(f"NumPy array: {numpy_array}, Type: {type(numpy_array)}")
# TODO: Convert to tensor
from_numpy = torch.from_numpy(numpy_array)
print(f"PyTorch tensor from NumPy: {from_numpy}, Type: {type(from_numpy)}")

NumPy array: [1 2 3 4], Type: <class 'numpy.ndarray'>
PyTorch tensor from NumPy: tensor([1, 2, 3, 4]), Type: <class 'torch.Tensor'>


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [23]:
pytorch_tensor = torch.tensor([5,6,7,8])
print(f"PyTorch tensor: {pytorch_tensor}, Type: {type(pytorch_tensor)}")
# TODO: Convert to NumPy
to_numpy = pytorch_tensor.numpy()
print(f"NumPy array from PyTorch: {to_numpy}, Type: {type(to_numpy)}")

PyTorch tensor: tensor([5, 6, 7, 8]), Type: <class 'torch.Tensor'>
NumPy array from PyTorch: [5 6 7 8], Type: <class 'numpy.ndarray'>


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [24]:
# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2,2)
print(f"Random tensor 1:\n{rand1}")

# TODO: Reset seed for second tensor
torch.manual_seed(77)
rand2 = torch.rand(2,2)
print(f"Random tensor 2:\n{rand2}")

# Check equality
print(f"Are tensors equal? {rand1 == rand2}")

Random tensor 1:
tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])
Random tensor 2:
tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])
Are tensors equal? tensor([[True, True],
        [True, True]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [25]:
# TODO: Set device
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cpu


### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [26]:
gpu_tensor = torch.tensor([10, 20, 30])
print(f"Original tensor: {gpu_tensor}, Device: {gpu_tensor.device}")

# TODO: Move to device
device = "cuda" if torch.cuda.is_available() else "cpu"
gpu_tensor = gpu_tensor.to(device)
print(f"Tensor on device: {gpu_tensor}, Device: {gpu_tensor.device}")

# TODO: Move back to CPU and to NumPy
cpu_numpy = gpu_tensor.cpu().numpy()
print(f"Tensor moved to CPU and converted to NumPy: {cpu_numpy}, Type: {type(cpu_numpy)}")

Original tensor: tensor([10, 20, 30]), Device: cpu
Tensor on device: tensor([10, 20, 30]), Device: cpu
Tensor moved to CPU and converted to NumPy: [10 20 30], Type: <class 'numpy.ndarray'>
